version: 2

project_name: terraform-provider-haproxy-dataplane

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-haproxy-dataplane
    main: .
    binary: terraform-provider-haproxy-dataplane_v{{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'

signs:
  - artifacts: checksum
    args:
      - '--batch'
      - '--yes'
      - '--detach-sign'
      - '--local-user'
      - '{{ .Env.GPG_FINGERPRINT }}'
      - '--output'
      - '${signature}'
      - '${artifact}'

release:
  draft: false
  extra_files:
    - glob: terraform-registry-manifest.json
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
