name: Release to GitHub

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g. v0.1.1)'
        required: true
        type: string

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Tag (manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git fetch --tags
          git checkout "${{ inputs.tag }}"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser (publish to GitHub)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --parallelism=1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          GITHUB_REPOSITORY: pderuiter/terraform-provider-haproxy-dataplane
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GOFLAGS: -p=1 -trimpath
          GOMAXPROCS: 1
          GOMEMLIMIT: 1024MiB
