// Code generated by scripts/gen_runtime_datasources.py. DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
)

func generatedDataSources() []func() datasource.DataSource {
	return append(generatedConfigDataSources(), generatedRuntimeDataSources()...)
}
