// Code generated by scripts/gen_datasources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ datasource.DataSource = (*versionDataSource)(nil)

func NewVersionDataSource() datasource.DataSource {
	return &versionDataSource{}
}

type versionDataSource struct {
	client *client.Client
}

type versionDataSourceModel struct {
	Value types.Int64  `tfsdk:"value"`
	ID    types.String `tfsdk:"id"`
}

func (d *versionDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_version"
}

func (d *versionDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"value": schema.Int64Attribute{Computed: true},
			"id":    schema.StringAttribute{Computed: true},
		},
	}
}

func (d *versionDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		d.client = client
	}
}

func (d *versionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state versionDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/configuration/version", map[string]string{})
	var out int64
	if err := d.client.GetJSON(ctx, path, query, &out); err != nil {
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	state.Value = types.Int64Value(out)
	state.ID = types.StringValue(strings.Join([]string{"version"}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
