// Code generated by scripts/gen_runtime_resources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ resource.Resource = (*runtime_mapResource)(nil)

func NewRuntimeMapResource() resource.Resource {
	return &runtime_mapResource{}
}

type runtime_mapResource struct {
	client *client.Client
}

type runtime_mapModel struct {
	ID   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Spec types.Object `tfsdk:"spec"`
}

func (r *runtime_mapResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_runtime_map"
}

func (r *runtime_mapResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs, ok := schemaAttributesFor("map_entries")
	if !ok {
		resp.Diagnostics.AddError("Schema not found", "map_entries")
		return
	}
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id":   schema.StringAttribute{Computed: true},
			"name": schema.StringAttribute{Required: true},
			"spec": schema.SingleNestedAttribute{Required: true, Attributes: attrs},
		},
	}
}

func (r *runtime_mapResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		r.client = client
	}
}

func (r *runtime_mapResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan runtime_mapModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := objectToMap(ctx, plan.Spec)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload["name"] = plan.Name.ValueString()
	query := url.Values{}
	path := buildPath("/services/haproxy/runtime/maps/{name}", map[string]string{
		"name": plan.Name.ValueString(),
	})
	if err := r.client.PutJSON(ctx, path, query, payload, nil); err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.Name.ValueString()}, "/"))
	plan.Spec, diags = mapToObject(ctx, mustSchemaAttrTypes("map_entries"), payload, []string{"name"})
	resp.Diagnostics.Append(diags...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *runtime_mapResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state runtime_mapModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/runtime/maps/{name}", map[string]string{
		"name": state.Name.ValueString(),
	})
	var out map[string]any
	if err := r.client.GetJSON(ctx, path, query, &out); err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	var diags diag.Diagnostics
	state.Spec, diags = mapToObject(ctx, mustSchemaAttrTypes("map_entries"), out, []string{"name"})
	resp.Diagnostics.Append(diags...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *runtime_mapResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan runtime_mapModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := objectToMap(ctx, plan.Spec)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload["name"] = plan.Name.ValueString()
	query := url.Values{}
	path := buildPath("/services/haproxy/runtime/maps/{name}", map[string]string{
		"name": plan.Name.ValueString(),
	})
	if err := r.client.PutJSON(ctx, path, query, payload, nil); err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.Name.ValueString()}, "/"))
	plan.Spec, diags = mapToObject(ctx, mustSchemaAttrTypes("map_entries"), payload, []string{"name"})
	resp.Diagnostics.Append(diags...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *runtime_mapResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state runtime_mapModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/runtime/maps/{name}", map[string]string{
		"name": state.Name.ValueString(),
	})
	if err := r.client.DeleteJSON(ctx, path, query, nil); err != nil {
		if client.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}
}

var _ resource.ResourceWithConfigure = (*runtime_mapResource)(nil)
