// Code generated by scripts/gen_runtime_datasources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ datasource.DataSource = (*runtime_DataSource)(nil)

func NewRuntimeDataSource() datasource.DataSource {
	return &runtime_DataSource{}
}

type runtime_DataSource struct {
	client *client.Client
}

type runtime_DataSourceModel struct {
	Items types.Dynamic `tfsdk:"items"`
	ID    types.String  `tfsdk:"id"`
}

func (d *runtime_DataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_runtime_"
}

func (d *runtime_DataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"items": schema.DynamicAttribute{Computed: true},
			"id":    schema.StringAttribute{Computed: true},
		},
	}
}

func (d *runtime_DataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		d.client = client
	}
}

func (d *runtime_DataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state runtime_DataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/runtime", map[string]string{})
	var out []map[string]any
	if err := d.client.GetJSON(ctx, path, query, &out); err != nil {
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	items, diags := listObjectsFromSchema(ctx, "endpoint", out)
	resp.Diagnostics.Append(diags...)
	state.Items = types.DynamicValue(items)
	state.ID = types.StringValue(strings.Join([]string{"runtime_"}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
