// Code generated by scripts/gen_datasources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ datasource.DataSource = (*crt_loadDataSource)(nil)

func NewCrtLoadDataSource() datasource.DataSource {
	return &crt_loadDataSource{}
}

type crt_loadDataSource struct {
	client *client.Client
}

type crt_loadDataSourceModel struct {
	CrtStore types.String  `tfsdk:"crt_store"`
	Items    types.Dynamic `tfsdk:"items"`
	ID       types.String  `tfsdk:"id"`
}

func (d *crt_loadDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_crt_load"
}

func (d *crt_loadDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"crt_store": schema.StringAttribute{Required: true},
			"items":     schema.DynamicAttribute{Computed: true},
			"id":        schema.StringAttribute{Computed: true},
		},
	}
}

func (d *crt_loadDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		d.client = client
	}
}

func (d *crt_loadDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state crt_loadDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{
		"crt_store": []string{state.CrtStore.ValueString()},
	}
	path := buildPath("/services/haproxy/configuration/crt_loads", map[string]string{})
	var out []map[string]any
	if err := d.client.GetJSON(ctx, path, query, &out); err != nil {
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	items, diags := listObjectsFromSchema(ctx, "crt_load", out)
	resp.Diagnostics.Append(diags...)
	state.Items = types.DynamicValue(items)
	state.ID = types.StringValue(strings.Join([]string{"crt_load"}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
