// Code generated by scripts/gen_datasources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ datasource.DataSource = (*mailer_entryDataSource)(nil)

func NewMailerEntryDataSource() datasource.DataSource {
	return &mailer_entryDataSource{}
}

type mailer_entryDataSource struct {
	client *client.Client
}

type mailer_entryDataSourceModel struct {
	MailersSection types.String `tfsdk:"mailers_section"`
	Items          types.List   `tfsdk:"items"`
	ID             types.String `tfsdk:"id"`
}

func (d *mailer_entryDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mailer_entry"
}

func (d *mailer_entryDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	attrs, ok := schemaAttributesForDataSource("mailer_entry")
	if !ok {
		resp.Diagnostics.AddError("Schema not found", "mailer_entry")
		return
	}
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"mailers_section": schema.StringAttribute{Required: true},
			"items":           schema.ListNestedAttribute{Computed: true, NestedObject: schema.NestedAttributeObject{Attributes: attrs}},
			"id":              schema.StringAttribute{Computed: true},
		},
	}
}

func (d *mailer_entryDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		d.client = client
	}
}

func (d *mailer_entryDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state mailer_entryDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{
		"mailers_section": []string{state.MailersSection.ValueString()},
	}
	path := buildPath("/services/haproxy/configuration/mailer_entries", map[string]string{})
	var out []map[string]any
	if err := d.client.GetJSON(ctx, path, query, &out); err != nil {
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	items, diags := listObjectsFrom(ctx, mustSchemaAttrTypes("mailer_entry"), out)
	resp.Diagnostics.Append(diags...)
	state.Items = items
	state.ID = types.StringValue(strings.Join([]string{"mailer_entry"}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
