// Code generated by scripts/gen_runtime_resources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ resource.Resource = (*runtime_backend_serverResource)(nil)

func NewRuntimeBackendServerResource() resource.Resource {
	return &runtime_backend_serverResource{}
}

type runtime_backend_serverResource struct {
	client *client.Client
}

type runtime_backend_serverModel struct {
	ID         types.String `tfsdk:"id"`
	ParentName types.String `tfsdk:"parent_name"`
	Name       types.String `tfsdk:"name"`
	Spec       types.Object `tfsdk:"spec"`
}

func (r *runtime_backend_serverResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_runtime_backend_server"
}

func (r *runtime_backend_serverResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs, ok := schemaAttributesFor("runtime_add_server")
	if !ok {
		resp.Diagnostics.AddError("Schema not found", "runtime_add_server")
		return
	}
	for _, k := range []string{"parent_name", "name"} {
		delete(attrs, k)
	}
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true},
			"parent_name": schema.StringAttribute{Required: true},
			"name":        schema.StringAttribute{Required: true},
			"spec":        schema.SingleNestedAttribute{Required: true, Attributes: attrs},
		},
	}
}

func (r *runtime_backend_serverResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		r.client = client
	}
}

func (r *runtime_backend_serverResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan runtime_backend_serverModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := objectToMapWithSchema(ctx, plan.Spec, "runtime_add_server")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload["name"] = plan.Name.ValueString()
	query := url.Values{}
	path := buildPath("/services/haproxy/runtime/backends/{parent_name}/servers", map[string]string{
		"parent_name": plan.ParentName.ValueString(),
		"name":        plan.Name.ValueString(),
	})
	if err := r.client.PostJSON(ctx, path, query, payload, nil); err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.ParentName.ValueString(), plan.Name.ValueString()}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *runtime_backend_serverResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state runtime_backend_serverModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/runtime/backends/{parent_name}/servers/{name}", map[string]string{
		"parent_name": state.ParentName.ValueString(),
		"name":        state.Name.ValueString(),
	})
	var out map[string]any
	if err := r.client.GetJSON(ctx, path, query, &out); err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *runtime_backend_serverResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan runtime_backend_serverModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := objectToMapWithSchema(ctx, plan.Spec, "runtime_add_server")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload["name"] = plan.Name.ValueString()
	query := url.Values{}
	path := buildPath("/services/haproxy/runtime/backends/{parent_name}/servers/{name}", map[string]string{
		"parent_name": plan.ParentName.ValueString(),
		"name":        plan.Name.ValueString(),
	})
	if err := r.client.PutJSON(ctx, path, query, payload, nil); err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.ParentName.ValueString(), plan.Name.ValueString()}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *runtime_backend_serverResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state runtime_backend_serverModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/runtime/backends/{parent_name}/servers/{name}", map[string]string{
		"parent_name": state.ParentName.ValueString(),
		"name":        state.Name.ValueString(),
	})
	if err := r.client.DeleteJSON(ctx, path, query, nil); err != nil {
		if client.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}
}

var _ resource.ResourceWithConfigure = (*runtime_backend_serverResource)(nil)
