// Code generated by scripts/gen_resources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ resource.Resource = (*crt_loadResource)(nil)

func NewCrtLoadResource() resource.Resource {
	return &crt_loadResource{}
}

type crt_loadResource struct {
	client *client.Client
}

type crt_loadModel struct {
	ID          types.String `tfsdk:"id"`
	Certificate types.String `tfsdk:"certificate"`
	CrtStore    types.String `tfsdk:"crt_store"`
	Spec        types.Object `tfsdk:"spec"`
}

func (r *crt_loadResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_crt_load"
}

func (r *crt_loadResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs, ok := schemaAttributesFor("crt_load")
	if !ok {
		resp.Diagnostics.AddError("Schema not found", "crt_load")
		return
	}
	for _, k := range []string{"certificate"} {
		delete(attrs, k)
	}
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true},
			"certificate": schema.StringAttribute{Required: true},
			"crt_store":   schema.StringAttribute{Required: true},
			"spec":        schema.SingleNestedAttribute{Required: true, Attributes: attrs},
		},
	}
}

func (r *crt_loadResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		r.client = client
	}
}

func (r *crt_loadResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan crt_loadModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := objectToMapWithSchema(ctx, plan.Spec, "crt_load")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	path := buildPath("/services/haproxy/configuration/crt_loads", map[string]string{
		"certificate": plan.Certificate.ValueString(),
	})
	if err := applyWithVersionRetry(ctx, r.client, func(version int64) error {
		query := url.Values{
			"version":   []string{int64ToString(version)},
			"crt_store": []string{plan.CrtStore.ValueString()},
		}
		return r.client.PostJSON(ctx, path, query, payload, nil)
	}); err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.Certificate.ValueString(), plan.CrtStore.ValueString()}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *crt_loadResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state crt_loadModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{
		"crt_store": []string{state.CrtStore.ValueString()},
	}
	path := buildPath("/services/haproxy/configuration/crt_loads/{certificate}", map[string]string{
		"certificate": state.Certificate.ValueString(),
	})
	var out map[string]any
	if err := r.client.GetJSON(ctx, path, query, &out); err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *crt_loadResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan crt_loadModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := objectToMapWithSchema(ctx, plan.Spec, "crt_load")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	path := buildPath("/services/haproxy/configuration/crt_loads/{certificate}", map[string]string{
		"certificate": plan.Certificate.ValueString(),
	})
	if err := applyWithVersionRetry(ctx, r.client, func(version int64) error {
		query := url.Values{
			"version":   []string{int64ToString(version)},
			"crt_store": []string{plan.CrtStore.ValueString()},
		}
		return r.client.PutJSON(ctx, path, query, payload, nil)
	}); err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.Certificate.ValueString(), plan.CrtStore.ValueString()}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *crt_loadResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state crt_loadModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	path := buildPath("/services/haproxy/configuration/crt_loads/{certificate}", map[string]string{
		"certificate": state.Certificate.ValueString(),
	})
	if err := applyWithVersionRetry(ctx, r.client, func(version int64) error {
		query := url.Values{
			"version":   []string{int64ToString(version)},
			"crt_store": []string{state.CrtStore.ValueString()},
		}
		return r.client.DeleteJSON(ctx, path, query, nil)
	}); err != nil {
		if client.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}
}

var _ resource.ResourceWithConfigure = (*crt_loadResource)(nil)
