// Code generated by scripts/gen_datasources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ datasource.DataSource = (*defaultDataSource)(nil)

func NewDefaultDataSource() datasource.DataSource {
	return &defaultDataSource{}
}

type defaultDataSource struct {
	client *client.Client
}

type defaultDataSourceModel struct {
	Items types.List   `tfsdk:"items"`
	ID    types.String `tfsdk:"id"`
}

func (d *defaultDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_default"
}

func (d *defaultDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	attrs, ok := schemaAttributesForDataSource("defaults")
	if !ok {
		resp.Diagnostics.AddError("Schema not found", "defaults")
		return
	}
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"items": schema.ListNestedAttribute{Computed: true, NestedObject: schema.NestedAttributeObject{Attributes: attrs}},
			"id":    schema.StringAttribute{Computed: true},
		},
	}
}

func (d *defaultDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		d.client = client
	}
}

func (d *defaultDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state defaultDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/configuration/defaults", map[string]string{})
	var out []map[string]any
	if err := d.client.GetJSON(ctx, path, query, &out); err != nil {
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	items, diags := listObjectsFrom(ctx, mustSchemaAttrTypes("defaults"), out)
	resp.Diagnostics.Append(diags...)
	state.Items = items
	state.ID = types.StringValue(strings.Join([]string{"default"}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
