// Code generated by scripts/gen_resources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ resource.Resource = (*frontend_ssl_front_useResource)(nil)

func NewFrontendSslFrontUseResource() resource.Resource {
	return &frontend_ssl_front_useResource{}
}

type frontend_ssl_front_useResource struct {
	client *client.Client
}

type frontend_ssl_front_useModel struct {
	ID         types.String `tfsdk:"id"`
	ParentName types.String `tfsdk:"parent_name"`
	Index      types.Int64  `tfsdk:"index"`
	Spec       types.Object `tfsdk:"spec"`
}

func (r *frontend_ssl_front_useResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_frontend_ssl_front_use"
}

func (r *frontend_ssl_front_useResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs, ok := schemaAttributesFor("ssl_front_use")
	if !ok {
		resp.Diagnostics.AddError("Schema not found", "ssl_front_use")
		return
	}
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true},
			"parent_name": schema.StringAttribute{Required: true},
			"index":       schema.Int64Attribute{Required: true},
			"spec":        schema.SingleNestedAttribute{Required: true, Attributes: attrs},
		},
	}
}

func (r *frontend_ssl_front_useResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		r.client = client
	}
}

func (r *frontend_ssl_front_useResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan frontend_ssl_front_useModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := objectToMap(ctx, plan.Spec)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload["index"] = int64ToString(plan.Index.ValueInt64())
	version, err := getConfigVersion(ctx, r.client)
	if err != nil {
		resp.Diagnostics.AddError("Unable to read configuration version", err.Error())
		return
	}
	query := url.Values{
		"version": []string{int64ToString(version)},
	}
	path := buildPath("/services/haproxy/configuration/frontends/{parent_name}/ssl_front_uses", map[string]string{
		"parent_name": plan.ParentName.ValueString(),
		"index":       int64ToString(plan.Index.ValueInt64()),
	})
	if err := r.client.PostJSON(ctx, path, query, payload, nil); err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.ParentName.ValueString(), int64ToString(plan.Index.ValueInt64())}, "/"))
	plan.Spec, diags = mapToObject(ctx, mustSchemaAttrTypes("ssl_front_use"), payload, []string{"index"})
	resp.Diagnostics.Append(diags...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *frontend_ssl_front_useResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state frontend_ssl_front_useModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/configuration/frontends/{parent_name}/ssl_front_uses/{index}", map[string]string{
		"parent_name": state.ParentName.ValueString(),
		"index":       int64ToString(state.Index.ValueInt64()),
	})
	var out map[string]any
	if err := r.client.GetJSON(ctx, path, query, &out); err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	var diags diag.Diagnostics
	state.Spec, diags = mapToObject(ctx, mustSchemaAttrTypes("ssl_front_use"), out, []string{"index"})
	resp.Diagnostics.Append(diags...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *frontend_ssl_front_useResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan frontend_ssl_front_useModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := objectToMap(ctx, plan.Spec)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload["index"] = int64ToString(plan.Index.ValueInt64())
	version, err := getConfigVersion(ctx, r.client)
	if err != nil {
		resp.Diagnostics.AddError("Unable to read configuration version", err.Error())
		return
	}
	query := url.Values{
		"version": []string{int64ToString(version)},
	}
	path := buildPath("/services/haproxy/configuration/frontends/{parent_name}/ssl_front_uses/{index}", map[string]string{
		"parent_name": plan.ParentName.ValueString(),
		"index":       int64ToString(plan.Index.ValueInt64()),
	})
	if err := r.client.PutJSON(ctx, path, query, payload, nil); err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.ParentName.ValueString(), int64ToString(plan.Index.ValueInt64())}, "/"))
	plan.Spec, diags = mapToObject(ctx, mustSchemaAttrTypes("ssl_front_use"), payload, []string{"index"})
	resp.Diagnostics.Append(diags...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *frontend_ssl_front_useResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state frontend_ssl_front_useModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	version, err := getConfigVersion(ctx, r.client)
	if err != nil {
		resp.Diagnostics.AddError("Unable to read configuration version", err.Error())
		return
	}
	query := url.Values{
		"version": []string{int64ToString(version)},
	}
	path := buildPath("/services/haproxy/configuration/frontends/{parent_name}/ssl_front_uses/{index}", map[string]string{
		"parent_name": state.ParentName.ValueString(),
		"index":       int64ToString(state.Index.ValueInt64()),
	})
	if err := r.client.DeleteJSON(ctx, path, query, nil); err != nil {
		if client.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}
}

var _ resource.ResourceWithConfigure = (*frontend_ssl_front_useResource)(nil)
