// Code generated by scripts/gen_datasources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ datasource.DataSource = (*peer_entryDataSource)(nil)

func NewPeerEntryDataSource() datasource.DataSource {
	return &peer_entryDataSource{}
}

type peer_entryDataSource struct {
	client *client.Client
}

type peer_entryDataSourceModel struct {
	PeerSection types.String `tfsdk:"peer_section"`
	Items       types.List   `tfsdk:"items"`
	ID          types.String `tfsdk:"id"`
}

func (d *peer_entryDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_peer_entry"
}

func (d *peer_entryDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	attrs, ok := schemaAttributesForDataSource("peer_entry")
	if !ok {
		resp.Diagnostics.AddError("Schema not found", "peer_entry")
		return
	}
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"peer_section": schema.StringAttribute{Required: true},
			"items":        schema.ListNestedAttribute{Computed: true, NestedObject: schema.NestedAttributeObject{Attributes: attrs}},
			"id":           schema.StringAttribute{Computed: true},
		},
	}
}

func (d *peer_entryDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		d.client = client
	}
}

func (d *peer_entryDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state peer_entryDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{
		"peer_section": []string{state.PeerSection.ValueString()},
	}
	path := buildPath("/services/haproxy/configuration/peer_entries", map[string]string{})
	var out []map[string]any
	if err := d.client.GetJSON(ctx, path, query, &out); err != nil {
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	items, diags := listObjectsFrom(ctx, mustSchemaAttrTypes("peer_entry"), out)
	resp.Diagnostics.Append(diags...)
	state.Items = items
	state.ID = types.StringValue(strings.Join([]string{"peer_entry"}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
