// Code generated by scripts/gen_datasources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ datasource.DataSource = (*globalDataSource)(nil)

func NewGlobalDataSource() datasource.DataSource {
	return &globalDataSource{}
}

type globalDataSource struct {
	client *client.Client
}

type globalDataSourceModel struct {
	Spec types.Object `tfsdk:"spec"`
	ID   types.String `tfsdk:"id"`
}

func (d *globalDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_global"
}

func (d *globalDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	attrs, ok := schemaAttributesForDataSource("global")
	if !ok {
		resp.Diagnostics.AddError("Schema not found", "global")
		return
	}
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"spec": schema.SingleNestedAttribute{Computed: true, Attributes: attrs},
			"id":   schema.StringAttribute{Computed: true},
		},
	}
}

func (d *globalDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		d.client = client
	}
}

func (d *globalDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state globalDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/configuration/global", map[string]string{})
	var out map[string]any
	if err := d.client.GetJSON(ctx, path, query, &out); err != nil {
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	obj, diags := mapToObject(ctx, mustSchemaAttrTypes("global"), out, []string{})
	resp.Diagnostics.Append(diags...)
	state.Spec = obj
	state.ID = types.StringValue(strings.Join([]string{"global"}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
