// Code generated by scripts/gen_datasources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ datasource.DataSource = (*log_forward_log_targetDataSource)(nil)

func NewLogForwardLogTargetDataSource() datasource.DataSource {
	return &log_forward_log_targetDataSource{}
}

type log_forward_log_targetDataSource struct {
	client *client.Client
}

type log_forward_log_targetDataSourceModel struct {
	Items types.List   `tfsdk:"items"`
	ID    types.String `tfsdk:"id"`
}

func (d *log_forward_log_targetDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_log_forward_log_target"
}

func (d *log_forward_log_targetDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	attrs, ok := schemaAttributesForDataSource("log_target")
	if !ok {
		resp.Diagnostics.AddError("Schema not found", "log_target")
		return
	}
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"items": schema.ListNestedAttribute{Computed: true, NestedObject: schema.NestedAttributeObject{Attributes: attrs}},
			"id":    schema.StringAttribute{Computed: true},
		},
	}
}

func (d *log_forward_log_targetDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		d.client = client
	}
}

func (d *log_forward_log_targetDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state log_forward_log_targetDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/configuration/log_forwards/{parent_name}/log_targets", map[string]string{})
	var out []map[string]any
	if err := d.client.GetJSON(ctx, path, query, &out); err != nil {
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	items, diags := listObjectsFrom(ctx, mustSchemaAttrTypes("log_target"), out)
	resp.Diagnostics.Append(diags...)
	state.Items = items
	state.ID = types.StringValue(strings.Join([]string{"log_forward_log_target"}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
