// Code generated by scripts/gen_resources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ resource.Resource = (*frontend_backend_switching_ruleResource)(nil)

func NewFrontendBackendSwitchingRuleResource() resource.Resource {
	return &frontend_backend_switching_ruleResource{}
}

type frontend_backend_switching_ruleResource struct {
	client *client.Client
}

type frontend_backend_switching_ruleModel struct {
	ID         types.String  `tfsdk:"id"`
	ParentName types.String  `tfsdk:"parent_name"`
	Spec       types.Dynamic `tfsdk:"spec"`
}

func (r *frontend_backend_switching_ruleResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_frontend_backend_switching_rule"
}

func (r *frontend_backend_switching_ruleResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id":          schema.StringAttribute{Computed: true},
			"parent_name": schema.StringAttribute{Required: true},
			"spec":        schema.DynamicAttribute{Required: true},
		},
	}
}

func (r *frontend_backend_switching_ruleResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		r.client = client
	}
}

func (r *frontend_backend_switching_ruleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan frontend_backend_switching_ruleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := dynamicToObjectsWithSchema(ctx, plan.Spec, "backend_switching_rule")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	path := buildPath("/services/haproxy/configuration/frontends/{parent_name}/backend_switching_rules", map[string]string{
		"parent_name": plan.ParentName.ValueString(),
	})
	if err := applyWithVersionRetry(ctx, r.client, func(version int64) error {
		query := url.Values{
			"version": []string{int64ToString(version)},
		}
		return r.client.PutJSON(ctx, path, query, payload, nil)
	}); err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.ParentName.ValueString()}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *frontend_backend_switching_ruleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state frontend_backend_switching_ruleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/configuration/frontends/{parent_name}/backend_switching_rules", map[string]string{
		"parent_name": state.ParentName.ValueString(),
	})
	var out []map[string]any
	if err := r.client.GetJSON(ctx, path, query, &out); err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *frontend_backend_switching_ruleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan frontend_backend_switching_ruleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := dynamicToObjectsWithSchema(ctx, plan.Spec, "backend_switching_rule")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	path := buildPath("/services/haproxy/configuration/frontends/{parent_name}/backend_switching_rules", map[string]string{
		"parent_name": plan.ParentName.ValueString(),
	})
	if err := applyWithVersionRetry(ctx, r.client, func(version int64) error {
		query := url.Values{
			"version": []string{int64ToString(version)},
		}
		return r.client.PutJSON(ctx, path, query, payload, nil)
	}); err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.ParentName.ValueString()}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *frontend_backend_switching_ruleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state frontend_backend_switching_ruleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
}

var _ resource.ResourceWithConfigure = (*frontend_backend_switching_ruleResource)(nil)
