// Code generated by scripts/gen_resources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ resource.Resource = (*defaultResource)(nil)

func NewDefaultResource() resource.Resource {
	return &defaultResource{}
}

type defaultResource struct {
	client *client.Client
}

type defaultModel struct {
	ID   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Spec types.Object `tfsdk:"spec"`
}

func (r *defaultResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_default"
}

func (r *defaultResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs, ok := schemaAttributesFor("defaults")
	if !ok {
		resp.Diagnostics.AddError("Schema not found", "defaults")
		return
	}
	for _, k := range []string{"name"} {
		delete(attrs, k)
	}
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id":   schema.StringAttribute{Computed: true},
			"name": schema.StringAttribute{Required: true},
			"spec": schema.SingleNestedAttribute{Required: true, Attributes: attrs},
		},
	}
}

func (r *defaultResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		r.client = client
	}
}

func (r *defaultResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan defaultModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := objectToMapWithSchema(ctx, plan.Spec, "defaults")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload["name"] = plan.Name.ValueString()
	path := buildPath("/services/haproxy/configuration/defaults", map[string]string{
		"name": plan.Name.ValueString(),
	})
	if err := applyWithVersionRetry(ctx, r.client, func(version int64) error {
		query := url.Values{
			"version": []string{int64ToString(version)},
		}
		return r.client.PostJSON(ctx, path, query, payload, nil)
	}); err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.Name.ValueString()}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *defaultResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state defaultModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/configuration/defaults/{name}", map[string]string{
		"name": state.Name.ValueString(),
	})
	var out map[string]any
	if err := r.client.GetJSON(ctx, path, query, &out); err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *defaultResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan defaultModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := objectToMapWithSchema(ctx, plan.Spec, "defaults")
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload["name"] = plan.Name.ValueString()
	path := buildPath("/services/haproxy/configuration/defaults/{name}", map[string]string{
		"name": plan.Name.ValueString(),
	})
	if err := applyWithVersionRetry(ctx, r.client, func(version int64) error {
		query := url.Values{
			"version": []string{int64ToString(version)},
		}
		return r.client.PutJSON(ctx, path, query, payload, nil)
	}); err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.Name.ValueString()}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *defaultResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state defaultModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	path := buildPath("/services/haproxy/configuration/defaults/{name}", map[string]string{
		"name": state.Name.ValueString(),
	})
	if err := applyWithVersionRetry(ctx, r.client, func(version int64) error {
		query := url.Values{
			"version": []string{int64ToString(version)},
		}
		return r.client.DeleteJSON(ctx, path, query, nil)
	}); err != nil {
		if client.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}
}

var _ resource.ResourceWithConfigure = (*defaultResource)(nil)
