// Code generated by scripts/gen_runtime_datasources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ datasource.DataSource = (*runtime_ssl_ca_file_entryDataSource)(nil)

func NewRuntimeSslCaFileEntryDataSource() datasource.DataSource {
	return &runtime_ssl_ca_file_entryDataSource{}
}

type runtime_ssl_ca_file_entryDataSource struct {
	client *client.Client
}

type runtime_ssl_ca_file_entryDataSourceModel struct {
	Name  types.String `tfsdk:"name"`
	Index types.Int64  `tfsdk:"index"`
	Spec  types.Object `tfsdk:"spec"`
	ID    types.String `tfsdk:"id"`
}

func (d *runtime_ssl_ca_file_entryDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_runtime_ssl_ca_file_entry"
}

func (d *runtime_ssl_ca_file_entryDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	attrs, ok := schemaAttributesForDataSource("ssl_certificate")
	if !ok {
		resp.Diagnostics.AddError("Schema not found", "ssl_certificate")
		return
	}
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"name":  schema.StringAttribute{Required: true},
			"index": schema.Int64Attribute{Required: true},
			"spec":  schema.SingleNestedAttribute{Computed: true, Attributes: attrs},
			"id":    schema.StringAttribute{Computed: true},
		},
	}
}

func (d *runtime_ssl_ca_file_entryDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		d.client = client
	}
}

func (d *runtime_ssl_ca_file_entryDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var state runtime_ssl_ca_file_entryDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/runtime/ssl_ca_files/{name}/entries/{index}", map[string]string{
		"name":  state.Name.ValueString(),
		"index": int64ToString(state.Index.ValueInt64()),
	})
	var out map[string]any
	if err := d.client.GetJSON(ctx, path, query, &out); err != nil {
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	obj, diags := mapToObject(ctx, mustSchemaAttrTypes("ssl_certificate"), out, []string{})
	resp.Diagnostics.Append(diags...)
	state.Spec = obj
	state.ID = types.StringValue(strings.Join([]string{"runtime_ssl_ca_file_entry"}, "/"))
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}
