// Code generated by scripts/gen_resources.py. DO NOT EDIT.
package provider

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/pderuiter/terraform-provider-haproxy-dataplane/internal/client"
)

var _ resource.Resource = (*cacheResource)(nil)

func NewCacheResource() resource.Resource {
	return &cacheResource{}
}

type cacheResource struct {
	client *client.Client
}

type cacheModel struct {
	ID   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Spec types.Object `tfsdk:"spec"`
}

func (r *cacheResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cache"
}

func (r *cacheResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs, ok := schemaAttributesFor("cache")
	if !ok {
		resp.Diagnostics.AddError("Schema not found", "cache")
		return
	}
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id":   schema.StringAttribute{Computed: true},
			"name": schema.StringAttribute{Required: true},
			"spec": schema.SingleNestedAttribute{Required: true, Attributes: attrs},
		},
	}
}

func (r *cacheResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	client, diags := getClient(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	if client != nil {
		r.client = client
	}
}

func (r *cacheResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan cacheModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := objectToMap(ctx, plan.Spec)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload["name"] = plan.Name.ValueString()
	version, err := getConfigVersion(ctx, r.client)
	if err != nil {
		resp.Diagnostics.AddError("Unable to read configuration version", err.Error())
		return
	}
	query := url.Values{
		"version": []string{int64ToString(version)},
	}
	path := buildPath("/services/haproxy/configuration/caches", map[string]string{
		"name": plan.Name.ValueString(),
	})
	if err := r.client.PostJSON(ctx, path, query, payload, nil); err != nil {
		resp.Diagnostics.AddError("Create failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.Name.ValueString()}, "/"))
	plan.Spec, diags = mapToObject(ctx, mustSchemaAttrTypes("cache"), payload, []string{"name"})
	resp.Diagnostics.Append(diags...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *cacheResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state cacheModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	query := url.Values{}
	path := buildPath("/services/haproxy/configuration/caches/{name}", map[string]string{
		"name": state.Name.ValueString(),
	})
	var out map[string]any
	if err := r.client.GetJSON(ctx, path, query, &out); err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	var diags diag.Diagnostics
	state.Spec, diags = mapToObject(ctx, mustSchemaAttrTypes("cache"), out, []string{"name"})
	resp.Diagnostics.Append(diags...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *cacheResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan cacheModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := objectToMap(ctx, plan.Spec)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload["name"] = plan.Name.ValueString()
	version, err := getConfigVersion(ctx, r.client)
	if err != nil {
		resp.Diagnostics.AddError("Unable to read configuration version", err.Error())
		return
	}
	query := url.Values{
		"version": []string{int64ToString(version)},
	}
	path := buildPath("/services/haproxy/configuration/caches/{name}", map[string]string{
		"name": plan.Name.ValueString(),
	})
	if err := r.client.PutJSON(ctx, path, query, payload, nil); err != nil {
		resp.Diagnostics.AddError("Update failed", err.Error())
		return
	}
	plan.ID = types.StringValue(strings.Join([]string{plan.Name.ValueString()}, "/"))
	plan.Spec, diags = mapToObject(ctx, mustSchemaAttrTypes("cache"), payload, []string{"name"})
	resp.Diagnostics.Append(diags...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *cacheResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state cacheModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	version, err := getConfigVersion(ctx, r.client)
	if err != nil {
		resp.Diagnostics.AddError("Unable to read configuration version", err.Error())
		return
	}
	query := url.Values{
		"version": []string{int64ToString(version)},
	}
	path := buildPath("/services/haproxy/configuration/caches/{name}", map[string]string{
		"name": state.Name.ValueString(),
	})
	if err := r.client.DeleteJSON(ctx, path, query, nil); err != nil {
		if client.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Delete failed", err.Error())
		return
	}
}

var _ resource.ResourceWithConfigure = (*cacheResource)(nil)
