// Code generated by scripts/gen_runtime_resources.py. DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

func generatedResources() []func() resource.Resource {
	return append(generatedConfigResources(), generatedRuntimeResources()...)
}
