// Code generated by scripts/gen_runtime_resources.py. DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

func generatedRuntimeResources() []func() resource.Resource {
	return []func() resource.Resource{
		NewRuntimeAclEntryResource,
		NewRuntimeBackendServerResource,
		NewRuntimeMapResource,
		NewRuntimeMapEntryResource,
	}
}
