// Code generated by scripts/gen_runtime_datasources.py. DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
)

func generatedRuntimeDataSources() []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewRuntimeDataSource,
		NewRuntimeAclDataSource,
		NewRuntimeAclEntryDataSource,
		NewRuntimeAcmeDataSource,
		NewRuntimeBackendServerDataSource,
		NewRuntimeInfoDataSource,
		NewRuntimeMapDataSource,
		NewRuntimeMapEntryDataSource,
		NewRuntimeSslCaFileDataSource,
		NewRuntimeSslCaFileEntryDataSource,
		NewRuntimeSslCertDataSource,
		NewRuntimeSslCrlFileDataSource,
		NewRuntimeSslCrtListDataSource,
		NewRuntimeSslCrtListEntryDataSource,
		NewRuntimeStickTableDataSource,
		NewRuntimeStickTableEntryDataSource,
	}
}
